# Generated by Django 6.1.1 on 2026-09-03 14:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True, verbose_name='Slug')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Sous-titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('category', models.CharField(default='Sportif', max_length=50, verbose_name='Catégorie')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/images/', verbose_name='Image de couverture')),
                ('video', models.FileField(blank=True, null=True, upload_to='articles/videos/', verbose_name='Vidéo')),
                ('video_url', models.URLField(blank=True, help_text='Optionnel : lien vers une vidéo hébergée ailleurs (YouTube, etc.)', verbose_name='Lien vidéo (YouTube/externe)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='À la une')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='published', max_length=10, verbose_name='Statut')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publié le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('content', models.TextField(verbose_name='Commentaire')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Approuvé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-created_at'],
            },
        ),
    ]
